#name: projections
# conda install r-base r-essentials r-lme4 gdal netcdf4 rpy2

dependencies:
  - click
  - fiona
  - gdal
  - joblib
  - matplotlib
  - netCDF4
  - pandas
  - r2py @ git+https://github.com/ricardog/r2py
  - rasterio
  - shapely
  - xlrd
  - r-base
  - r-essentials
  - r-lme4
  - pip:
    - pylru
    - geopy
